[package]
name = "next-error-code-swc-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
swc_core = { version = "5.0.*", features = ["ecma_plugin_transform"] }
